version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=your_db_name
  #     - POSTGRES_USER=your_db_user
  #     - POSTGRES_PASSWORD=your_db_password

volumes:
  postgres_data:
