version: '3.9'
services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    # depends_on:
    #   - db

  # frontend:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=
  #     - POSTGRES_USER=
  #     - POSTGRES_PASSWORD=-
  

# volumes:
#   postgres_data:
