# Generated by Django 5.0.6 on 2024-07-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocrprocess",
            old_name="processed_text",
            new_name="ocr_text",
        ),
        migrations.RemoveField(
            model_name="codesnippet",
            name="text_content",
        ),
    ]
